In [14]:
import numpy as np
lt = [1,2,3,4,5,6,7,8,9]
out = np.array(lt)
print(out)

[1 2 3 4 5 6 7 8 9]


In [37]:
import numpy as np
array1=np.array([[1,2,3],[4,5,6],[7,8,9]],ndmin=3)
array2=np.array([[9,8,7],[6,5,4],[3,2,1]],ndmin=3)
result=np.multiply(array1,array2)
print(result)

[[[ 9 16 21]
  [24 25 24]
  [21 16  9]]]


In [42]:
import numpy as np
array1=np.array([[1,2,3],[4,5,6],[7,8,9]])
array2=np.array([[9,8,7],[6,5,4],[3,2,1]])
result=np.add(array1,array2)
print(result)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [1]:
# array(object, dytpe = None, ndmin)
import numpy as np
lst = [[2,4,1], [6,2,1]]
arr = np.array(lst)
print(arr)


[[2 4 1]
 [6 2 1]]


In [2]:
# array(object, dytpe = None, ndmin)
import numpy as np
lst1 = [[2,4,1], [6,2,1]]
lst2 =[[2,4,1], [6,2,1]]
arr = np.array(lst1)
arr2 = np.array(lst2)

print(arr)
print(arr2)

[[2 4 1]
 [6 2 1]]
[[2 4 1]
 [6 2 1]]


In [3]:
arr.shape

(2, 3)

In [5]:
arr.shape = 3,2
print(arr)

[[2 4]
 [1 6]
 [2 1]]


In [14]:
import numpy as np
lst1 = [[2,4,1], [6,2,1]]
lst2 =[[2,4,1], [6,2,1]]
out  = np.add(lst1, lst2)
print(out)



[[ 4  8  2]
 [12  4  2]]


In [24]:
# add two matrix using numpy

import numpy as np
lst1 = [[2,4,1], [6,2,1]]
lst2 =[[2,4,1], [6,2,1]]

arr1 = np.array(lst1)
arr2 = np.array(lst2)

# add two matrix using numpy

if arr1.shape ==arr2.shape:
    out = np.add(arr1, arr2)

    print("matrix 1")
    print(arr1)

    print("matrix 2")
    print(arr2)

    print("Result")
    print(out)

else:
    print('Shape is not valid dor operation')


matrix 1
[[2 4 1]
 [6 2 1]]
matrix 2
[[2 4 1]
 [6 2 1]]
Result
[[ 4  8  2]
 [12  4  2]]


In [27]:
# multiply two matrix using numpy

import numpy as np
lst1 = [[2,4,1], [6,2,1]]
lst2 =[[2,4,1], [6,2,1], [1,4,1]]

arr1 = np.array(lst1)
arr2 = np.array(lst2)

# multiply two matrix using numpy

if arr1.shape[1] ==arr2.shape[0]:
    out = np.dot(arr1, arr2)

    print("matrix 1")
    print(arr1)

    print("matrix 2")
    print(arr2)

    print("Result")
    print(out)

else:
    print('Shape is not valid dor operation')

matrix 1
[[2 4 1]
 [6 2 1]]
matrix 2
[[2 4 1]
 [6 2 1]
 [1 4 1]]
Result
[[29 20  7]
 [25 32  9]]


In [7]:
import numpy as np

a = [[1,2,3], [4,5,6], [7,8,9]]
b = [[9,8,7], [6,5,4], [3,2,1]]

a = np.array(a)
b = np.array(b)

out = np.multiply(a, b)
print(out)

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [10]:
import numpy as np

a = [[1,2,3], [4,5,6], [7,8,9]]
b = [[9,8,7], [6,5,4], [3,2,1]]

a = np.array(a)
b = np.array(b)

out = np.dot(a, b)
print(out)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [14]:

a = [[1,2,3], [4,5,6], [7,8,9]]
b = [[9,8,7], [6,5,4], [3,2,1]]
mul = [[0,0,0], [0,0,0], [0,0,0]]

for i in range(len(a)):
    for j in range(len(b)):
        for k in range(len(b)):
            mul[i][j] += a[i][k] * b[k][j]
for i in mul:
    print(*i, sep = '\t')

30	24	18
84	69	54
138	114	90


In [11]:
import numpy as np

# arange()

out = list(range(1,10))
print(out)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [25]:
import numpy as np

# arange()

out = np.arange(1,10)
print(out, type(out))

[1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [38]:
import numpy as np

# arange()

out = np.arange(1,10, .5)
print(out)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [43]:
import numpy as np

# arange()

out = np.arange(1,13).reshape(3,4)
print(out)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [78]:
import numpy as np

# linespace(start, end, width)

out = np.linspace(1,10,5)
print(out)

[ 1.    3.25  5.5   7.75 10.  ]


In [79]:
import numpy as np

# linespace(start, end, width)

out = np.linspace(1,2, 20)
print(out)

[1.         1.05263158 1.10526316 1.15789474 1.21052632 1.26315789
 1.31578947 1.36842105 1.42105263 1.47368421 1.52631579 1.57894737
 1.63157895 1.68421053 1.73684211 1.78947368 1.84210526 1.89473684
 1.94736842 2.        ]


In [84]:
out = np.zeros((3,4))

print(out)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [86]:
out = np.ones((3,4))

print(out)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [98]:
out = np.eye(6,6)

print(out)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
