In [1]:
st = input()
d1 = {i: st.count(i) for i in st}
print(d1)

{'a': 2, 'j': 1, 'l': 2}


In [2]:
st = input()
d = {i: st.count(i) for i in st}
print(d)

{'b': 1, 'a': 3, 'n': 2}


In [7]:
st = input()
d = {i: st.count(i) for i in st}
print(d)

{'a': 2, 'j': 1, 'l': 2}


In [6]:
out = print('Hello') or print('Python')
print(out, type(out))

Hello
Python
None <class 'NoneType'>


In [9]:
out = print('Hello') and print('Python')
print(out, type(out))

Hello
None <class 'NoneType'>


In [21]:
# prime no. using while loop

n = int(input('Enter a no.: '))
i = 2
if n == 1 or n == 0:
    print('Not prime')
else:
    while i < n:
        if n % i == 0:
            print('Not prime')
            break
        i += 1
    else:
        print('Prime')


Not prime


In [ ]:
n = int(input('Enter a no.: '))
i = 2
if n == 0 or n == 1:
    print('Not prime')
else:
    while i < n:
        if n%i == 0:
            print('Not prime')
            break
        i += 1
    else:
        print('Prime')

In [25]:
n = int(input('Enter a no.: '))
if n == 0 or n == 1:
    print('Not prime')
else:
    for i in range(2,n):
        if n%i == 0:
            print('Not prime')
            break
    else:
        print('Prime')

Not prime


In [4]:
# polycap

l1 = list(map(int, input().split()))
l2 = list(map(lambda x: l1.count(x), l1))
print(max(l2))

2


In [39]:
l1 = list(map(int, input().split()))
l = []
for i in l1:
    l.append(l1.count(i))
print(max(l))

3


In [ ]:
l1 = list(map(int, input().split()))
l2 = list(map(lambda x: l1.count(x), l1))
print(max(l2))

In [ ]:
l1 = list(map(int, input().split()))
l2 = list(map(lambda x: l1.count(x), l1))
print(max(l2))

In [43]:
a = int(input())
b = int(input())
c = int(input())
if a >= b and a >= c:
    print(a)
elif b >= a and b >= c:
    print(b)
else:
    print(c)

3


In [45]:
lt = list(map(int, input().split()))
l1 = list(filter(lambda x: x%2 == 0, lt))
print(l1)

[2, 4]


In [46]:
lis1 = [1, 2, 3, 4, 5]
def even(x): return x % 2 == 0
lis2 = list(filter(even, lis1))
print(lis2)

[2, 4]


In [47]:
lt = list(map(int, input().split()))
l1 = list(filter(lambda x: x%2 == 0, lt))
print(l1)

[2, 4, 6]


In [48]:
f = open("sample.txt", 'r')
data = f.readlines()
for i in data:
    if i[0] == 'a' or i[0] == 'A':
        print(i, end='')
f.close()

Ajlal
Anas
Abu


In [26]:
f = open("sample.txt", 'r')
data = f.read()
count = 0
lt = list((data.split('\n')))
for i in lt:
    for j in i:
        if j.isalpha():
            count += 1
print(count)
for i in lt:
    if i[0] in 'aeiouAEIOU':
        print(i)
f.close()

21
Ajlal
Anas
Abu


In [62]:
def sumsquare(lt):
    l1 = []
    l2 = []
    for i in lt:
        if i%2 == 0:
            l1.append(i)
        else:
            l2.append(i)
    a = 0
    b = 0
    for i in l1:
        a += i**2
    for i in l2:
        b += i**2
    return [b, a]

lt = list(map(int, input().split()))
data = sumsquare(lt)
print(data)

[35, 0]


In [65]:
def sumsquare(lt):
    l1 = list(filter(lambda x: x%2 == 0, lt))
    l2 = list(filter(lambda x: x%2 != 0, lt))
    l3 = list(map(lambda x: x**2, l1))
    l4 = list(map(lambda x: x**2, l2))
    return [sum(l4), sum(l3)]

lt = list(map(int, input().split()))
print(sumsquare(lt))

[35, 0]


In [63]:
try:
    try:
        raise TypeError
    except ValueError:
        print("inner Exception handled ")
    print("next command")
except TypeError:
    print("outer Exception handled")
else:
    print("no Exceptions")

outer Exception handled


In [67]:
st = input()
dt = {i: st.count(i) for i in st}
print(dt)

{'b': 1, 'a': 3, 'm': 2}


In [1]:
st = input()
d = {i: st.count(i) for i in st}
print(d)

{'a': 2, 'j': 1, 'l': 2}


In [36]:
import numpy as np

n = int(input())
l1 = []
l2 = []
for i in range(n):
    m1 = list(map(int, input().split()))
    l1.append(m1)

for i in range(n):
    m2 = list(map(int, input().split()))
    l2.append(m2)

mul = np.dot(l1, l2)
print(mul)
for i in mul:
    print(*i)

[[ 6 12 18]
 [ 6 12 18]
 [ 6 12 18]]
6 12 18
6 12 18
6 12 18


In [7]:
lt = [(1,2), (3,4), (5,6)]
dt = dict(lt)
print(dt)

{1: 2, 3: 4, 5: 6}


In [8]:
num = int(input())
dt = {1: "One", 2: "Two", 3: "Three", 4: "Four", 5: "Five", 6: "Six", 7: "Seven", 8: "Eight", 9: "Nine", 0: "Zero"}
for i in str(num):
    print(dt.get(int(i)), end=' ')

One Four Three 

In [8]:
f = open('demo.txt')
data = f.read()
print(data)
lt = data.split()
lt1 = sorted(lt, key=len)
a = lt1[-1]
# print(a)
for i in lt1:
    if len(i) == len(a):
        print(i)
f.close()


Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias commodi culpa reprehenderit iste perferendis officiis
laborum iusto! Tempore, perspiciatis, aliquam pariatur facere deserunt repellendus error quas culpa quae cupiditate
ipsam odit blanditiis, corrupti quo doloremque animi non nemo sunt! Sint nostrum, tenetur ducimus necessitatibus saepe
esse iste dolore fuga eveniet! necessitatibup
necessitatibus
necessitatibup


In [21]:
f = open('demo.txt')
data = f.read()
lt = data.split('\n')
lt1 = sorted(lt, key=len)
a = lt1[-1]
for i in lt1:
    if len(i) == len(a):
        print(i)

f.close()

ipsam odit blanditiis, corrupti quo doloremque animi non nemo sunt! Sint nostrum, tenetur ducimus necessitatibus saepe


In [23]:
f1 = open('demo.txt')
f2 = open('sample.txt')
out = open('output.txt', 'w')
data1 = f1.read()
data2 = f2.read()
out.write(data1)
out.write(data2)
f1.close()
f2.close()
out.close()

In [25]:
def apna(lt):
    l1 = list(filter(lambda x: x%2 == 0, lt))
    l2 = list(filter(lambda x: x%2 != 0, lt))
    l3 = list(map(lambda x: x**2, l1))
    l4 = list(map(lambda x: x**2, l2))
    return [sum(l4), sum(l3)]

lt = list(map(int, input().split()))
print(apna(lt))

[35, 0]


In [28]:
a = {1: 2, 3: 4, 5: 6}
print(a.get(8))

None


In [35]:
import random

a = [1, 2, 3, 4, 5]
s = random.getstate()
m = random.choice(a)
print(m)
random.setstate(s)
n = random.choice(a)
print(n)

5
5


In [38]:
m1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
m2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
add = [[m1[i][j]+m2[i][j] for j in range(len(m1[0]))]for i in range(len(l1))]
print(add)
for i in add:
    print(*i)

[[2, 4, 6], [8, 10, 12], [14, 16, 18]]
2 4 6
8 10 12
14 16 18


In [46]:
import numpy as np

mat1 = [[3, 5, 6], [5,5,8],[4,4,4]]
mat2 = [[3, 1, 1], [4, 3, 4], [3, 5, 0]]

mul = np.dot(mat1, mat2)
mul2 = np.multiply(mat1, mat2)
print(mul)
print(mul2)
for i in mul:
    print(*i)
for i in mul2:
    print(*i)

[[47 48 23]
 [59 60 25]
 [40 36 20]]
[[ 9  5  6]
 [20 15 32]
 [12 20  0]]
47 48 23
59 60 25
40 36 20
9 5 6
20 15 32
12 20 0


In [48]:
Enemy, Friend = 5, 2
st = 'No Better Friend No Worse Enemy'.split()
re = st[Enemy%20] and None if Enemy + Friend < len(st) else st[Friend%20]
print(re, eval(re))

Friend 2


In [49]:
a = print('HEllo') or print('Hi')
print(a, type(a))

HEllo
Hi
None <class 'NoneType'>


In [50]:
l1 = list(map(int, input().split()))
l2 = list(map(lambda x: l1.count(x), l1))
print(max(l2))

2


In [51]:
l1 = [1, 2, 3, 4, 5, 6, 7, 8, 9]
l2 = list(filter(lambda x: x%2 == 0, l1))
print(l2)

[2, 4, 6, 8]


In [ ]:
n = int(input('Enter no of rows: '))
l1 = []
l2 = []
for i in range(l1):
    m1 = list(map(int, input().split()))
    l1.append(m1)


In [52]:
f = open('sample.txt')
data = f.read()
lt = data.split('\n')
for i in lt:
    if i[0] == 'A':
        print(i)
f.close()

Ajlal
Anas
Abu


In [53]:
f = open('output.txt')
data = f.read()
l = []
for i in data:
    if i.isalpha():
        l.append(i)
print(len(l))
lt = data.split('\n')
for i in lt:
    if i[0] in 'AEIOUaeiou':
        print(i)

360
ipsam odit blanditiis, corrupti quo doloremque animi non nemo sunt! Sint nostrum, tenetur ducimus necessitatibus saepe
esse iste dolore fuga eveniet! necessitatibupAjlal
Anas
Abu


In [54]:
def sumsquare(lt):
    even = list(filter(lambda x: x%2==0, lt))
    odd = list(filter(lambda x: x%2!=0, lt))
    l1 = sum(list(map(lambda x: x**2, even)))
    l2 = sum(list(map(lambda x: x**2, odd)))
    return [l2, l1]

# main
lt = list(map(int, input().split()))
out = sumsquare(lt)
print(out)

[35, 0]


In [70]:
int('a')

ValueError: invalid literal for int() with base 10: 'a'

In [80]:
st = input()
d = {i: st.count(i) for i in st}
print(d)

{'a': 2, 'j': 1, 'l': 2}


In [82]:
a = int(input())

ValueError: invalid literal for int() with base 10: 'dsc'

In [6]:
a = int(input())
i = 2
while i<=2:
    if a%i == 0:
        print('Not Prime')
        break
    i += 1
else:
    print('Prime')
        

Not Prime


In [ ]:
a = int(input())
i = 2
while i<=2:
    if a%i ==0:
        print('Not Prime')
        break
    i += 1
else:
    print('Prime')

In [1]:
import cmath

n = complex(input())
print(n)

(1+2j)


In [32]:
l =  [['Harry', 37.21], ['Berry', 37.21], ['Tina', 37.2], ['Akriti', 41], ['Harsh', 39]]
s = sorted(l, key=lambda x: x[1])
print(s)

[['Tina', 37.2], ['Harry', 37.21], ['Berry', 37.21], ['Harsh', 39], ['Akriti', 41]]


In [34]:
n = int(input())
l = []
for i in range(n):
    a = input()
    num = eval(input())
    lt = [a, num]
    l.append(lt)
print(l)
s = sorted(l, key=lambda x: x[1])
print(s)
l = 1
print(s[0][0])
for i in range(len(s)):
    if s[0][1]==s[l][1]:
        print(s[l][0])
        l= l+1


[['dc', 12], ['dcs', 12], ['dc', 54]]
[['dc', 12], ['dcs', 12], ['dc', 54]]
dc
dcs


In [42]:
n = int(input())
l = []
for i in range(n):
    a = input()
    num = eval(input())
    lt = [a, num]
    l.append(lt)
# print(l)
s = sorted(l, key=lambda x: x[1])
# print(s)
l = 1
lt2 = []
if s[0][1] != s[l][1]:   
    lt2.append(s[l][0])
    l = l+1
for i in range(len(s)-1):
    if s[l-1][1]==s[l][1]:
        lt2.append(s[l][0])
        l= l+1
        
lt2.sort()
for i in lt2:
    print(lt2)


[['ajlal', 100], ['anas', 100], ['ankit', 90], ['vibhanshu', 90], ['as', 54]]
[['as', 54], ['ankit', 90], ['vibhanshu', 90], ['ajlal', 100], ['anas', 100]]
['vibhanshu']
